[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "956601fa14cbfa6148f153553bd30cfbe8577c45"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "956597fc6dd0a1e19ead555e972b0f03f37dc2e8e15f5427bb45486ddcbca778"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de70a510ae985c41c9946860f8875fe5ed4376fe"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9cf9d81c22cb3045ad1530185b2cab3002e6e879da9fd70975d188211fe5e698"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb287094ef7c5d9a9f78ca88a53b7afd85dd160f"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "59cf11e7ce09ea85a0bade10789f286aa7b5f0a2de0dc45d6d7056df20f9a83e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfdd750d197f545f7746819d327cef5e96401b1a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "53d6a37e0b9218395018344dac5cf56522f4ae095b4c5b5ef538d6030b4867e8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6722b6f87bfc8134af1a14ac46adb5502a6ec7fe"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1f6effa7889f89cbbda543ee6b3ec93091259a89b16f9a72e2eeae26e6e90d87"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b01df46b40e9983d5bc0cf9e52357393e56b8fe4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3aeedc314661fc0e79baee24103f0ee2caa2d2b40f5a284ca453721663ff8cd0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "646bd9dd2591de361fbd08d943ebe9fd15031194"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "aa59db38d4036b07896141aa7aae1d6523dd07170ccdb9f285ee795e08e74be5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d17f79e396780dd8597bbe38596c3b65d275ab9"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "82d5f3a83d0919f3dc0c640ff28355a1724a530780486bb91200a4a558bf5ff2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f9eb3caeeac79018e61670d0440c28edd02caa7"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e700d04bb730d9f71d51a531f625369b62aa7552a17c58dc2c07ef1c9ff8673b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bd7154666100660a7809a4c9d4fe73d6c32ff11"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "cc68bd9a081f63fcfdad2b3c0fbd37cb7fd0151698429ddb32c840c4673f300d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eb78858b2e197ab34bc42381a004b0993a9ccd7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "eb4a623ca8c49f9a278986a75839ee509d8ddaa20522b740f95e755f00a2e12c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1717123179b2ee5901edf82aadbc610afef6178e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a4670fe7131390326f824baec497372f4b0d114d43e0091910d69675def0cda6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91f0130af13ec27e289f230cc9d4040c0a78728d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "925afa3082e2d9a0e283e8dd6b112004747928a5d8a59cb9dcc731370f01df2f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "079880db66dc5bad205b930a8692d17dd17b591a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "c94e60dd991921c2ed814ce712a22f8c92fb869dc980653a6400573b6e73c0db"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88d8ce2abc95dd8ae05c3293ef385127a0c12e7e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0cf6fc69a77bbf22fbd0cea66e42e61c5a6324c5dd4bf8b134899f6734cd0f75"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1778ae49504c8870993ab36278a2d0a3517b72e9"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "70969137166bb7dfaf0d2eebe313e79a27e4f4972c5addb9e5e0ad4d442be1de"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d766cf5953c6d339325da3a0519d53c084c7fbd"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4c37ac9f96b2b1c65cefddce106dab1748a2e9fcd548203f8cf5b18d9aeeaa86"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34fe9ed2326b01bcfea620fd42516c6e90473f04"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "56be5eca3e27c2628ac56d7f5bd3d9578ca33ba3dc4373565a3f2d44cfcb1a50"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1093446b1622bd7d85ba9c943c05026b092eca4"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "13d2a98f544a04576296fb606c057d8d081c433f8e1aad82c38d27e2cdc23c29"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64487067290a8043fab9527aebf5e7af77503da3"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "55fea9ed7ee6e7ae7df1fe146f85a780f9a31aaea8192a178a8fe0b17a020974"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e1fba194d44b1dafb194ab5d2a49019d4098aaf"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "02f5b60d84121e14b92fdb8a9719a8ddc62a947ba0a41093ab2d02c79003cbbf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "16e7691d9aea6ed2c74d7701a27522a629635fdb"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "36142f4134c499101ee4e409b6613217017fbb8a586630d22691bf6027280113"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4152ce8eae2d0cbddf90b9a77b9242f695b5925d"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a85bb44b0f5de5de114c077bedad1f04f192c2a26beb59139a15644f17c183a2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "293ba4b01841b34ebcba15e037a7160a1a436667"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "06bc4ce8296db6a2c9d67850f2d37c9d61302d408c51659d6996b3a915cf1b98"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0435b0295d662ca028049c4310b57ceabdac7375"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b0570dac727b00d1c8186b376458c1d1de72d80f5d9b78b33d96ffefd277cca3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de52b8d240908ab1255568dc24f642243f1f7ac3"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9809f71c7c81a9bdf37e6a7371426b259e36a49c618eb37d64598259f9194452"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "dc01ea08ddd07388478964be2ae87e68653b1e6b"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "c46e36eed7f23cbb21e606a00c71b85908026b35c2bdb79fc3709ad5468c7417"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86946380693b6ff05d77a0fb5c412823d6d2ceba"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "2b4a1069af7902922fcbb572c2299fdffbfa84ab9342390e850da83953ea56d2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbdddca09b8112ec04022173a7ddb2d8bba40307"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "56966cfdfd25db2bc734f1b6a569c054aff7890e04360c21530f3e431377f724"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+2/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
