[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "e50957467d64a225133a9d25c3f68901ab59c77c"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "0bf6862e67da86cadfde3f9daba60d10f4171df030cde7b02119b06a62dca876"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "430794be4b7418a0e2bb50dc354e319adaf5e387"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "077c38866186f20d13b61e0ed1bc863286537d926b56c896007ee6ab4860998f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ccb204266077619350700ebff63074bc5ab960e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fbf4b895a45fcbdf5c6595e74a4379c6e9e8060a2d742037adf417c68d633954"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc05f7d70c62f8e3015cce74073b65574511ab60"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "308285d40c9c9b2fe26b45d16feeb26e1f710907bf72aa41cff490588dbe1760"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9598c49b9f1910d40efb8db4f2f17c759aab6848"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a99e488aaf06c537de2b9bdfdf5a1800abedf620b6c46df5d5a3a29dcf0cb3a9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b9c55be15beefb52a913d7ce87c4e6da0d5a900"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "6360c1d52e0616e9374bba2204c6171c6ed54a6740cd2f6a25f9ee80eddaa09f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efaec8f7222004a07b5d32cb4a43a5d72af8e33a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "393a1e8ef863e4145cf1f54a7a4f2ca6010c72ce15ba0a4acc737bbe445f7d79"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "592784305a87aef56a625d37eb4b38f378c0d40b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "61bc9491cfa9a7fb887a5547b4e41e7f402a2ea5a3e50a70e891d342e79c6a7e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b569e02302742237f98153aa29c20ea8f0fa9b7f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4c851e9519735c5446699574f9f56f2b280c5b2d73ec8bc87bdd29622a7bb42d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abc41d1f89b0aa32257a7eca41518a0983842fce"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "aa28aa6e77ff888c394a3cff96af2e390fbb128fd4d29a76c62ceee6e48bfbec"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a24812fe55f96904122ff6d73567d64cafa00c2c"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0648fcc32fcd4d0f5726850c94db02967604cc04c4b66798192926d1f51d8feb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3895595a76332acb2f2041860708e721ae5cd2e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ea7c79012964547ad7c12e5d9e56558b3bee57878b54af47a7a7849eb82c7cd0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d58520fc1e24b0d47304a404e384fd7c5e2147"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5c36a5bc11461253a83ce1bed47353765fb800314501e1338fb014bc870d358c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10bdb439d48632ad0407919db8f2ed23aa059f5c"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "80cd78cf2a41211d4c066fe9475f61aeeeb0cb2e11ba022bcf9e26bd41181e56"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15650c02c9a5b2c5ee9caf358a862f74855719e0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1ea4e2c9c88fc8efff12557d48f2e8163f922f86c6142fcd6a6edc0ae83711dd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "829a0d5acaf8552a4ed998f38e28937cfe264a87"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1d6960ab1f86cda6ea55dadeafebdd4d7ec8fd8a6e313600a81837f10dbd5242"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7cf1c8c603dbbbee02f7dd91dac2b14b66d215a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "dc3bd3f3ad2c51b5ae3bea0c3f27db576a511616c89860b32cacc362fa736fe1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83a70de38e2ae558ad1fb8a0694585ae1516620d"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "c070046f6543b9c02109166e277200a8d14e5825653f859b840a5c5a25ba816f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b03fd9747b9742bf4ccf0e7492fd2b084ad49c2f"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "a28d137ba6a0d2ff0f60c235254180170f829cc5b0849cc688d048e267b8096b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32de7ce2230e42bbd47d8bbc269621eb65a2df5e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a2b8691e5ad3ed014d58e1ebffa8e8e2505f26a2907c67face8316b8f18161e7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77139899dc4efebc2c489421b32673848b160cf7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5f991661500553f438445bc38baef6b4c05f4ef32351f43f56f1e84e9a86baa7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "4906885b054f4c2353e9262f94178d752e2d95e7"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "43e56497d8f3daa8d64df039cc6a5c2b89fcc46b9914b9ebb68e5ffb0d509dd0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75325ee1405f606c74eebc503b7201e7dbf00be0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "c54c5ed6954a1ce70a08ad76e6f334f6cd911978a88c067ecb4fbc9af8525280"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43ed1c5fe7a2fd6749923fd849d41412fec0b1de"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d721389d392845d427b487d35ddd07ec78cc5a9b229a075b26f01c89ff5bc291"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f215f2000517241a173e80f299ceb9fa4973b77"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f3f97fb8259a0901b858c07cce6512a64ae03a967754c910008d53bcf3c85148"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d412a28fb7012d2e0fe5fe875e4afc51ddd3ed70"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5f5113a0fc64990ac3aeee741597931597d1ddfb12bb1328f49d717976193f6f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "620ec5803e289e8af29659fdcbbe891eccf55813"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "02f43d4fc3ca1a5a37f172f6d50e34abe4cd8116808494d5f060fbe24b688bb4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ead7dfc1415065e5515e6ec45596009941a45f19"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "9596fcf0297d7cf2c305a31950db40e821224a3352eae2c7ce2ae46c28479692"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae5208731406836fab68658f67b46a3ea575dde3"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "45dc493476387fc285431f02eead453904686abfda9b5b3a7e082f47dda514c2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+0/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
