[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "d3b167ce5eca2290c1e19c503bcf334732b7a481"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "37b22c43e0bc753f53fd135cbb7476eaff76ebe64900502ef3c45b64e046a50c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34b6fa3ec5fedf38aa3ccc798dd7fb828f9e4c4a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b89df9017690b35cd78ded08c077dcf1eac547f046295630fd71680495b8f4d5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb77e2a5e22b774220a3edd2b4060f6fa6505039"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "34efaea48b8b9c89cc2482f2023aad7aefb285d7d52b4279a2fb53c0fbd5bff7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "062a6abd4fe71e07c8b921185a2d4c875b12a219"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d4f9316120bde3a034539ce611516d515b036d6b4f5a7adab89eb836821c0371"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1144256b104e3824d99e46dcbdf51a22fe2ee8b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2ef2fe2b1b3ed401927a4d6185ba992a01b12fe770d089a95b0cf9876de35a23"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96af20be949da57a92e29821f2a72123ff9d61a9"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ae65d4b1998324854b015ce1462a8badfac524d56dc786c1a1da0809d3996057"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "191da604ed1678935b367c0acf699324d4b9b57f"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f2ef79c9c3064e4f652e9e85d76411b5f1955aa1d67b2f4bc5710b344a665545"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e20afc8b2945845f8eed59e82443a9c32dfbc7c7"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7473e143e07f99ae7a16cc2fea4e2f778ac9269c3a0874e74b01da4902a9cf5a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bb8e4d479ce3754b08208e2787a6822a2655756"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "17ae01cb535f1dfeeb514d8ddec9f8bc0909b8666b4b0203c57af5695908657c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17294161bf40f6cf8de9ce6607c6586fba2817b3"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5bde9cc606b4986c29d11ba5a077d65d6b4fcaabeff289fbfbfd324e7ad95be0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a523a6342300ad008c9073f1d7ba1260e7bc58b"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a9287cb86a8e8da6adb1dfbf2c60141d9d30b30a27a978628d7f63cbdde17bba"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa0f036245d1757900243f40c406444a299a919d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0683ff4b4e8f528abe823730f7d12d15723ead78104869918f187c9cf6445682"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cf8d1bca82de361eb8ee29c0892084ad3b3be1e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "977df0cc553cb4c77efff6458ebebf4de837bc318c573c85d4b6fcef5a60a053"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcc8338f780b8e35a0d500fd9ef284e16f2a9787"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9326d331fbf37a6241e399613dcaf69e3481af30f17354518f1153865ec895b6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c281ecfdae01e7e8b2acb18ad4dcc881261b4bd4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "22d0f9ecf21fde6219af03ce7693c31d4f49b9f131d28c692b7c8a5b2bf5abd0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a17b7ad59abf7cc4e97224436eb669f6598f50f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fd6d9c0675722091ef61e32e417bf818a95bd461c91274b76681f74828a77043"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e86b2ff540c30d5b6f60ee185aacf75c7a630be"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fb5160a4bdef8c890c45230301996804354d762708f9ca1805b67fb389635677"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88793f52c2af20a1dfc52cad915584904da10343"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "bce9a6b7e8b652ed495c54cd0636737e944f8a2d176fefe0bfec4c36661fb2ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e35ee005b80aa2b21e6d7a0d4f0b675f8766f036"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "6b1206c6cde2bc0e5ba7500aee93b15106e0f5f3de0992f78b281ebc25ab6f08"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c64fd67628eff8255cadedf019af7a890d56cb9"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "38632c17f83c88bc6e733b53aa3414b15b755a2ed0e0119fa2b648e5ce76bd05"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c81edc823db2e6319b8359cfa6f688f779c5517"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3d803359070e788eb3298bbe23870a57f522e1b85632082a931db4f029a13d51"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "2ed0ced4e5984de419effcf6f63cf4125a56534c"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "30d27b1ef7d0e84b7c08783903ef2ca73a5b254e09eefc1bca87b2bd2025d098"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb966507b9464de2beb1c925e6a074f5cb45cbc2"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ebf83e7c9e62c1a6cfbfd308af593a45e7f494149a0582dac062120b3472cc86"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da0629391a2ddbf585de04720620130891f7f2ea"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2bccbbe38a4a42da2bd9bdb16c9e44a251abbd337da3239c1f0c8892b50b0f1d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e039c46aa3eac47b709f0e836c2ad7f6a60cb1dd"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8000c02344749b959609a5da89b34b336759c4f194fd64a2eccbb206431bc662"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "264a1094eea6b8276c990529fdd31de89674bccf"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5f01fdb6844ea5d949a8f9eebf72f2cfbc64699d311377331852918871dac790"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "3ee89294cfa7042097dc0e691d731f2ac7a2b18e"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "2a7be0afc7b49c1ebe97f1b3b0e589a28b2a571d3aee7b689483d0112c57f02e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0714dc78ad9d0d36842a1cfb562357f5765121f8"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "9e613c8c86b2b413943e1519feffb494f4ed2e46101cb05597ebcc9d820744a8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09b0879161603d4e6a4139a677a8c6f3a309cb27"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "55ffaeb00536f622b6f86c01aa3fee75b13e815df14d9bd0c5cbc68ad394bc7e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.0+1/libLLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
