[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "45cd4dc2037a65076cd20ea0ebfb437ff76c0d61"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "cd2fc44141c41bf3df9c4b8025baac3258c977b6dfec6bab0a9bf1c5630733e4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee9a78c5a9226d2b3380f4e6c491516c8b816c4d"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "406b74b8eb7a32592bc3907c68a84a1034dcabdae37109668906548dcfae8831"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bafa995f27a020050523d8c1540f914950adee5b"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "37f7e0b5049529e193175b3030c762ce46537266904fad2e6a2fd295e350b1b4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "394083509089a4f89360d2bc3ae2eea67aeed406"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5d2c6626dc16e9b0423648d5288229a02df058fb1b3c06dc8e6147efa90d4cba"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d79d629bcf947d4d0b8964ec54d84161930909c2"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4fefab5d4a5fc0af3fb8d9b827b8b4f7c4f7eec5a724b58349383f0d7ebd5666"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42041125dbac5b7fe3e49e8feefe538fea092f6d"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "78b10dadcd617c65896671921b59a813d9c3e8300416d9c904dd59abd6f99f16"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "619ce8e9af0049668d2a7b92ae6560e08533a982"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f9a6f5c1380db98e1e46168b7ac88feffc59358cba0170f08c2c702014834453"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49d5c8efe1eb1dcfeb8011f152cf17d0858090df"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0e7ba686c91abb84ed6372227526fd7640de8ed54c9d144e710ab92fed7ca283"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "462671858c138748d790518bf15063e619d4fd20"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7e024aeb58e4bc1f7f80ba5b9703a3ff5c83b20cc7bee788e4f18b74324fa9fc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f3d4403b63c7178e00870afff4716946c738099"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d67aade31dd7340909d034507572ca5bc38c5b7cf02acd444b6e76c48f4228c9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16e90d15b8049236f645c5dc5942fa79a52298b7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8423aaeab329da30f133fa6cae64c6a8510b5cbf9e0c176240c42b4d9383c319"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2c4328b4d724eede31d391d2af026a754c5838a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d9c1d1c6f084f65860e711b4a2602720987989fbd3af577d6149681b25fd8b9c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f691717a3e2e6ea0b8b36e0cc0d4c3f15d00612"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d0ce77bc859787a257c82c16ebf3267b52191a4851d8dd4a2a960f99869dc7c5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "903fa276e3187730d40938d7cf18ba547c7b29a5"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f275639aeb1e2389eecbcd048e3c84c9d760ff4b62ca7ac6f8e3cf867b9f26eb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "359f8793e70863ccf9997c4fbf4270abe351141e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "257c6ea4d4b6d169eca1e6379b856b1d53764fdf5b6c2b7911618b5916b1d320"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc90afcbc4e350afb01200fe5826f4c1a6387592"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "531c35ecda6171f70e2d1150dfe13f01d8d18961e649d0daa93d51dfafc82a18"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b6ee225176ab67c15452d00ddb1e13393db65df"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9304f4ea9d63c99c67a09d6f0932bc01e8272a44080c8e9d3f3c733191ce1f4a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4cc5de45ecbf1ac7603b77ac7a756ab47c1093f"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "0964407c7a43e63ff327fd0239cf68897fd33460d2efb84845ae83577af911dc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "289a74a7ec0c1f548f9580e2b74bf8aaf6ba94e9"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "f5a4376133c94b042198840252f15267070c881da428ec454827331b06905940"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08a9059b01f09439738859e91bb6408287f7cb53"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "56cd4602f958ad9aa71b01b7fddd62c41b5022336c23e4b3d565f4abd30522d3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "828ca176c15b678febfe66f0c63daca45fdd315a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ad1a118b6822e866b682f5a3855bc831abc8771401c027c3a55064263bb8de25"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "1907967c0b5746fba12a5b860119ad1633633785"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "e5a95f62d5aa3f002c20fa697cd537bd0d91c66390c8cf718e32d50774e76d81"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ba03a4f7c52bce40e3e1c072afefb97aeaa93b4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0e9ff20fb00ec76dd868ea254f8113f35569cf8dc2deba0dda39d81a720f1571"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d7d1585aa8c8a8910e5dea26b5bda112e4eccc0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9931c274cc29f25c9ee11682861256dcc28eb880e85765aef3ea04aef5b17993"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3172589e270cb654fdd9526fa863f9d0972db0bb"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "08657a6b8c18efafa1c6635ce04dc2b75fbec3ba6c811c4b8c92927d19667bce"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c4704666c4c8ae53706929aede4cdb33aec8e43"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e66a6481dea8baf02d27a0e8970d78a06ef07a08e1f563d484cb4a153e1f557d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "5244fa7d8b4783383426cbe0721c9fc7198751f4"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "e2f4e3087e2e001c8340d5a5cc7e7ecb679729177a79c8dc991bddea828f153e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6c8bff4bac0f7f16c39d8ea1c46a8e61915c967"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "c58ab7ede4b879e8ad913a19227e91d25043f06724df8924ff1a8f3c92bf215f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e4ed9b9a7eb79c5b043167e42c9c7628a96f4e"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "3b889b39d4dde6da37471633c2d6f48f86b9ae6f0e28c1847552a174dd2eb4c2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.0+3/libLLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
