[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "3053d43e6b7ca157495aad8851de21817a255e43"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "e81e707ce96be696ba3d057c0d1477e2f6a00092513652ebbfaa2d7baed5b17e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0c537e331fefdd332d4b460d9ff52eabd7c8fd9"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3e6165a022b567a9b30d104033ffc9152e2399b473f69ab2b843c12aeddeb16b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e533c3708fdfecc34b0eef0a329248f07014667"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d8335fd61cfc92b160dcd051092c824eda98b6bfbc132212e8dcc7254365bf3a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be7e0a6619d1084c49802ab91f9451943b16aaf9"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "315267a0c14730ec268301ed9ef04353206462c235494e13e8e43ab2a2d2cbfb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90b90d3f419d30ebec2e0a4e6aa8f47c4fa7710f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4c8c07f2414de66f1cc5cf67db540f390aa0ccdc8dffc41d5fefede1bd084b44"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "561c4281fc7f39b9bee1a23d1364855dc13bf250"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a292ac7110edbd19c5dd99606e91a54b0c33666dc3427db1a737efdb349e85c6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bca038f0f5fde7006c4218ae8492741b563765a4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b3c7b841c299bb37fa953ebd654d7bf2b28986af58554a8152c41973be3c8b4a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c6193e50ef2defa80aaecfb4261aeafc0c7d0af"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e0e1c37d31152923f7f2e767928877a0ef39c6643bd2498ad0e02dae1d639534"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e39e563bc128523c1a2c2061f1c3d20fc84f5ce8"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8ec1611c6d4154f2cf5e611fc76ff803d9f173576fbe5b404910f31baae6dc61"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bcfee9f3a795623a021cb999cf57d2b148b46e2"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "38ec478fb78eb39c4baaf989e33b0647d07c19bc226d1006eef6c0c0870ab5ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90cefdee4d40fca213defdd4d86a4a7071c29e86"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8d4345fc98b363f2d4b116686627116be9e51c0c0365a5ce08f15f381ca17670"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3d21e155a44238d36eb1ee188b64012a2a60440"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "aba80b604dd904fd90c77959eca25d83bb6cd431da5feb4e8a70161b08ee59f9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f927c24f4edb16451380864b56d091ac7de0ac2"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ae4462e3db48ff77ec2da980beccd1ce1eee80512913f0230b75dac46405b857"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b271e0478fb5c284506a216b213ed88790ed2823"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8166727308ce844c94dfc07aa1f538fc29613a8fbbc73ecbb8deca22a5b6d685"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd84a17643d197ea018417f257325232bc82645c"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "68d9b1d0c1ad0e52372a8c165250c462efaaa5c9470f681a891e363b5f31c059"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78cdf3f3f31c322865125b5216214bb8ee1d1580"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "54840bc1bfcca869e0d416025c75eae4d537c094d5dcc9272d805cbe854ebc98"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c7ea2a0795a8b324f5e161842659699e62053c8"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d2d1391df873de81003938e5a83f11afe711a72adf57595d00c0b7900b50229d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "692c883a18dff0034b5bbe3f8eaee031a4d4041c"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "fc676b709cc8cab95c6b9bce3c7d19e11e00544785937ca6fe9bf56817fa7b58"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bed0276694f5b4d10617138f17d17a51f83a564"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "30198a4babf25f8d10d30083c1f5ea15fb642efc2ff05de6f1384c8e6aea36cf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c604d3dbfa9247e3ef608077aed73763c60d53fe"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ef68cc1638f498a283ec7e21704467b75fd4c9bd4a57a3179c5f2dd3039594f4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "064eef509f95e4aba0721b6584df55c612fd77a4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "36905ee86284faf12f441b0324da8e4e13f7e653f7163858f39736ca2c1a566c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "66acc3b6c9a899c44f0c0641b690c20b5ecde8ba"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "6c402e9d939cf5e766ecce413a4310e611ebca05c29370315b445e8d6092375b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adec398a56e8c68bcb64b7079e0a77870e59aaeb"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a42695a4c4ef11fb56f00306ac570f2c93243ff096f0a7bcb1317e8a33c7794d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a61e23d81b7dc3187f0035345b757afc9bd3918"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5b1cdb04bd00d790a28993b1382f25737c4741f9dc152efdf15c0bf058aa728a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8e6389b14c9873dd70cfc22ba3e54a7cac92581"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "30cdddbae17c79712920e3da81f7f158c4d29348ddd993193ef2f2e4928b82c3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76823e1f7b186b1b9525cb896966df857f88613b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "28cedacb4216cef71866a81942a10ba488ae093722f6ec1862177c55040aef4a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "efba1d0964bfde96ea4869dbdca01f45b3816ddb"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "91f46a36123885c85934855ee455fc2efdc4ba0dd2e442bcd6c5491ab187b27f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c490ffd77abe24eeef56d1b7e84120fb1770a8e3"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "cdd206468b919085aa5d9e3caf79f37894a5a3c2e650eb60e528c392c1d0aa3f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d633b64450d9cfa5435724ae3ec3c7d2c68aa6b5"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "caa3f16a80522ab2fa8a4d563fb3ca547bb7231d9d68e7d9c069e6ecf73b8a70"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+1/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
