[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "6652e7d39ffdee48668651fda2299400d00ea5c5"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "6b7dff58ffc1657a56021975a2a5b7cddb9178471fbae442e466cbfd26b901c3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c18f927f28db03797fd4879fcb3fe107fcdefd3"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e33f45945a872cf136fa2849d70a2c0f8366216a6a084e74c7e5a6b7e06d5e39"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65c6c7bc053964972905a4760e7457a923b5f9b0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "de758ea5d8dfa1df2fbd20cceab6c290202b07e6add328231765707b5a91f2c0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a99d0011badae9cebdc38a39790ec87af1f862d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e96e28797dc9e1df538ca02394838969c33bbe6703842c8303aa4684d8a4bf0a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eb53d148210519eaf2007937f4ad03595900eef"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5cc084a58bb74fade42ed55785d5c0c57feb95b3aa8a3bf4b27ac0ace4e4cc39"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3daad204140051aa91f9ea398b59488c356781ef"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f47b7943a8fcf1f2c1f2ad065294e581158c3d78b9db86edd908b1bd397c0c24"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94e550c8bb55f2da948caf1eb5d0c34b23e8c225"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fcca8d9fada8e3e6aaaf8dd516146f4013e6e4f7514c4cf80f924e870b68a8d9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da073524c9fbbb3b49064c0ba57637a82da3d12f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e208f165c5e574b04c03827fc683535ecfaec8147f39c3260caab96517bbd37c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2814716dfe64c0b4e66bec4078ac0dde5cc655b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b4d698887d53fb8de72ec38c0a117b2526b1a904311e9e19a41dc1ef3871fafc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "550468a6fec30d94cd6ae62d0825e5a22f8ad2b7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "09207f9e40d8b365bc54f99b1bc4b05cdcdd01cc7c7e0c7f065bbffb1c36cdfd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5128005783ba8b40070e59437403d4ffac9fb8ca"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d9f6e25463de03730535e9418773ef1690c184283f85c908d0ac243e6e8d94ae"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79badd85e386dcfe6b1854da913fb7922cc9b770"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "afec25bae357e9540c94b28246e8818ad7f1d3180f583ee6297a117ee18024a0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9d3f1ec62b3f864dbcc8bfd33eaba0a7010a7af"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "76fc807e7f951a48b9a2c07d683023eb39bdfd3342ca266777cca6704b5145f2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab93eaeb46421028fd630eab817ba1a70c1d3f44"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8eb8fbf1ed4df64c61dac70ca4c935c8efd790c137d6e076465e49745b9dd159"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbbb94472a13aa6f1926b6038ae9652ab16d8cc8"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2ae3e89107816993b18dc35d12029c37dda5c0636b28270b395a141ce09b1666"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "869760b6f383533c041059d7e824707c0921a225"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5e01f6eadace9ffe3cfebeaa13a8631d453f149e6ca8b9badde27b896ea21ae8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aae49998178ed177fc89d6759cbbe2d7d5a069b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0c571d489755fa992961240dd9f3c6143998e06ca4cb85ecfb2002c8294fe97b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cf335f42f8c94a14d13f2230e7c6f096d6a8a44"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "31508242d239ad6422f1de361b4865056bc684d94a1ca8a76b0dc2f7ce781443"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d5c8c875e180475e85ea4c29704f9e83ce7e6b2"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "e5520bac2d25dba6c1b7bde5fb93cd450a600a45c1302c237c97e56d3f1ff4f2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4346f03a7b354ce0beb84bfffc34fa85f12448bd"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ecdc56943d627378ee62a4faca84868a58e1f434c4fe39da870b5d2e7cad2a15"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "507c79dcc2799b94414eb628e7a3fe02edc5284d"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0daa9f60e50074dd8edc87b5630a8bcbadcb21ad30843993eefafdbfe88230fe"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "e57c68038d752076799cae6047ae62950c9dabf5"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "223f4bbc009b85ac793a006553014a1b96c2f8295f02968be67f4daf84128702"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f99cd4250173a46de2e1b5984ca6717d929ea89"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b43040c6ee0e5f7b18163db3f1ac216e485b01408e3833cc73abd82178ca45e0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b4a43c37d7f7c85651858eb2b2e4b40b510d748"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5a7da45896be53c78c4c3e54e3548fea1b6b2438418efd7cdc6a511938d23a80"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4acb1df8a5f7a24c63e771301ac52e3599a9311e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7c088c0f3f4de0c548cbdc90c6f7d4d2c22124edbb5f45eeb0a137a60080c45e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b24ed4efa3cfefd9e03c7e5fff8a8d5d68bcff10"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e348928718041f150c4d047485d7b6849e1b69ebab68a27384d363ce281220ee"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "32ac2baa96a3e4c6a5eedf1b6db279092f56d2ee"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "1f375caedc996d46f9a5e8a1f361446fd06cd7776b8e0168956a33cea5124a5e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2726b9ace1f1934b35e225eda1db7afea0f917f"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "f3f22c7c0b067fc0928e9524fa9cd0305db806250a47b2127aa56aafbd7deb13"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29b670e8ae7857927dab2fb1b5a1531eb40f165e"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "57ed488f64cd4bce55ac36f89dc7c70c2aa85fc8722ec3bf190f467da9d85c80"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+2/libLLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
