[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "602d61e1607d29c28564a35fbc237e31be2e2b5c"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "12f7d6221928960dbaa7d2e773d4dc4e21696108f42fd635e66e37252bbfbc56"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b14111e117f0c114fd891e1637a3e076b1acbb3"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b254628a7c3c669336043cf95034cf05fb3f5f3c80c6606a661c50cffa8ae07f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9f6ae09d12863f17cad0d0ee8478345b643e8ea"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "01220139f028b2610dd194e1dd3d39cec1bcaa0a88e469aff0505cdff541f8f1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aeee957d5fc8084c0dfde689d167204567aa70e3"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "72aa05a4b7c97ed8dafcd698772ce42e03f0442158e065b63a452f5ea16ee87f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a96aef0c8560ba89a8a830daa20b50943cc9e75b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a13762a3a6e6e0dc8ab6605b0a919d110717850fb979c60ae2b335a25cd0b0a5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3daad204140051aa91f9ea398b59488c356781ef"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "51cef5d40077dd3e5da5674fd2a8f9c3431c2fd82fc6b3d8ef50e745c8259af4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94e550c8bb55f2da948caf1eb5d0c34b23e8c225"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "861aca07ae8ead2f315449ecbcd5a772ba4277e4fe9b79627850cda2e8ad0beb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da073524c9fbbb3b49064c0ba57637a82da3d12f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "cf97a533e9269d1ef2277e0ee4797729ecb2cf57f2730f85d6359b3d2d2cc3dc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2814716dfe64c0b4e66bec4078ac0dde5cc655b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "737084fdd2c4c3bc66b6a3974d2d75530423d5a07c54ed250305d3c5c937bc9e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "550468a6fec30d94cd6ae62d0825e5a22f8ad2b7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e9eb14c7a45274cdc99840164d758b62667f028cb92004cd621bc7577a3229be"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5128005783ba8b40070e59437403d4ffac9fb8ca"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d0bdbe4267b80bcf71e1061ae92bb785cfdf780dcf674cd233e363953b9b3361"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79badd85e386dcfe6b1854da913fb7922cc9b770"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b817a8f3e3d3b32bbd1ca2d0b03c545c441ffe3fc918ad2739ce5437387aef5d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9d3f1ec62b3f864dbcc8bfd33eaba0a7010a7af"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2074e01c6ed2d49efd3ec95c4ce7010916f53991ebbd8d2cefbb246235ea1c2d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab93eaeb46421028fd630eab817ba1a70c1d3f44"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8d932c94cf0bd264dddadd8f86e68a96c2fcb0da24b26b042c16ce2f27ab2037"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbbb94472a13aa6f1926b6038ae9652ab16d8cc8"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ddd817d3aac746852a67ae202e92a0aa8b137ee3cd6fcecbfdc734f3f719b26d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "869760b6f383533c041059d7e824707c0921a225"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "08c7c0bbac8570cb3d6ee910661a62814f4f3b5d8f20d806ced43c269196dfc2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aae49998178ed177fc89d6759cbbe2d7d5a069b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4e9b119f7a95834a1532c5ee63469de9ab25ebbfdf49b6155a27f9c8195a4021"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "816dcfca9557c1427580691dcedf1380bb22772c"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "40f8a9eb2f93e9ce2f541c916d122c2e4d4c0f89fbfbc1df7c85baa79b651d05"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b4e90588b16f5f63a43af978ad114ada3ab9ed0"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "7a1bacd18dd786da28261c09d9a303e81d69febf1506c17bebe7ab5f1574dd56"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4346f03a7b354ce0beb84bfffc34fa85f12448bd"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5d72e043d1d6ee338d752b4db73b5ac04fd2fe76364646a697a2dce32d324381"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "507c79dcc2799b94414eb628e7a3fe02edc5284d"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7a96312ba1b99c25b4df0e6ba6bdf1b6362a868b1635ef4fdcf88ee522ab5252"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "e57c68038d752076799cae6047ae62950c9dabf5"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "8be7450baa6564d8ef09052f4ccc897bdd0751ba86c6e20a52aa7c6237b82792"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f99cd4250173a46de2e1b5984ca6717d929ea89"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "6600ce740fd8af233cae8de9f032bfdf5570b199e97762ea5ebc32efc67df618"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b4a43c37d7f7c85651858eb2b2e4b40b510d748"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ce193eefd1ee97ccff701a5380bb17d3f5fc2b61f6d70874dbd544aba8a60715"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4acb1df8a5f7a24c63e771301ac52e3599a9311e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1102227f1cc8bf47fe74796f62bb968cbb1f33b344627015c9bedb72caf7483d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b24ed4efa3cfefd9e03c7e5fff8a8d5d68bcff10"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5f90b1d453b97bfda8d483ffdce2310e0c95ae9d73251c0df619629a9575db65"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "32ac2baa96a3e4c6a5eedf1b6db279092f56d2ee"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "c61c57d8d5fca2f72c6b06673e14e424962605ba4bb360076f9b1db9d1a1c547"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ea6581502f8072b7f7ce7f078c0f4c1e62ef315"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "7e5a7d846bda1641b476c91a522b44f18e6f3c4abe6541af5a0bf3bd60dc3a69"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f64c6ce5cbc87973fde9b297999444b4e7834f1"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "6fd45bb97690d535ebbed251ef79d18170f4f46fc432babe9de8340d6277aac2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.1+3/libLLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
