[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "c946ebae7b51534da9fec100f419d5bbb63ccddb"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "4e94e7509b5afcdedd0ec3ae08073434b2a25e016baf99f2fe1bea77a8ecaeab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49d339c257776f3d1581d30cc0e6c85db2f88968"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e08408d3c1fa87bc3223f66ccdc840058d2a0d38b52ff4f2e32b177103df00c3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a20fb1cbb26316da287296c82260b0561f458f45"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d045d9012f31c3615ed42851b33bf68688cc73c1e7ac5e8f0f10a23e106d0e27"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c90564ca8f46d3334fc5f24f7bdc74819197783d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "64b02074e802acba67f99b775730b38b2608f9d7de6ab1088d12f8de17ee357d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4e051129478aed93e7af92a12599a522ac99eb4"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "269be1db0d22b1a3c9fac9cc17bef6172c6771beddb61971bf6ad242132c30aa"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "941989838529b7f063e2d518c2c2c78c0026b062"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "24591641249df8be41396eed6edccd4245d1d7edc9ce0ee8da725bf0dbd9104c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1208571033752099c000b53265b2938e9a31d075"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "956d32e8a44442c74caebcf3b4dfdfa4ee27fe13387cc97c495f6402a4adefc7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3302e6a5209dce2e6a1592de7b04f8c546097e90"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "af820a18a0a6745188e5d63c2d1cff02bd8a0b3c0115b050b12c6cdf6514a16b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2da64649edb7aed9e05fd781f39790a5fb241617"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ab48a66c6830b68517e44a9741219b3b1e17bb136841cd5ff40dbd52abed57ae"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41907b7dbabbde08970d4638c6b23b9e9570f014"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2f8491b231eb2c8c18ab16cc200938b24be6c2c94e1c38846866c837878a7eb5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a32cd46724c614f111e66bb0c5c924eb08444fa0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "426942503ac0ba9d9061d03a59fc77b46afd29cec9b9aedf3e1480668c2ce472"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e099ea6d35f11087085551f4f1379bc1490753d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "db1c6defa2a5e82f770b6734bd3cb860e35036bc721f12cc043132c877f905bb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e780d92130ce66fedcaa0affc709e68d56eb4389"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8a8b9b7fad48e0ab975c3f673dead5698ab5688b9728cc5a7ad8ed2e257b92bd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4dcb2881f85bc6395a83ee515c7d44cdcc97c2b8"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3f433dd8c77aa17cb2a320220b7f8efba4f26071f3595cf91412af2cee66364a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5c628720a8455cc8f1abf05248f0612394c5654"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7b0a292a6104e4ab7301e2a818060c42597a334f9a4aa2636d0b0a4782d453fc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98d0adc31f96b5032196de1a57d756a442d282e1"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0fa6838dbd2f1c887177d3642c334714f8e2aca7e387a564fab0a63114418f73"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebe52ae9347b8853b60c32ccb62858786d0cc6cc"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0a65da50d5411ee09c7e20bffee91e03af61c077f5463b295044b5697620209d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7353f387764b53f6873eb709bffd487c945348cc"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "efc22873bf3a5db7df146a12936559f9529e540d52a86a5c10ec7a06d5f531da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac9b6b96eeb55bb73869b1d0c778e189416e54ac"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "025fbb8af44aa296d763c5c45b05a622cde7d69989678a34afe472bd99c4fd19"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81827cc5ee9ac7c675135fa8d962b20cc01d0bfc"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2832319ea7522e718375e6fa6d1991780d3b0f56cca15ba720cf88292188aa8e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f388c2c0f77f4e04729ebdd8a1780aa0393fd5d8"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e2a9622d8febffcaf2b7b672adbc5f50a69695fed6c84b865f937c0cb76db428"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "7b7539db4586105f6912974c72660c2d240d05d5"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "3783f01e20873afa5194274d7443e10a0adf7b598c958524d85b1aa5b3cf328c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9ccc2821193edbcc5caaf90f9c3da25a9f836a0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9e21d10cba8c978d3b6fe675009c78b260deb834a9687bca35f95bd317beae86"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62615945cca51610c3566e6c44c39e6cf808c1c1"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b515cfdcc2a8bcbda1b9c80ef847fba23038afee044d8348f9c1a05d75f4c6d8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90b2287721493913dc4304c7d9375274fcf0d81d"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ac0b2c3f3fe5fdef2f338e6e13fb63fb08e01f658e04c16842685314bfa4a25b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0033c584a3836318a5663ab612517a4e3fdc5923"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "329cf29205e21e3079cc0bec5bedfa1200187d8ee58659dd87369be70a7f0cd6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "ce98dacfa65e1ffbf0a5d6acf55bd8a47fcf94fc"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "7e762a1a22612d2a740ee1f75af342bdf3eaa8221efaa11a7478283469490fe6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfcbc42dad29f266ad4358765b4bb5b91bf7e312"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "df3d37b3ae30c437a628db8f97221b065a8876225db5110011aab343525b80e7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "997f3df3fd9bc057e747b8d2fb2fd4df95c4f83e"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "25158bbf62c663bd0c65389797e76ab5e0f0b1bfdef555b38117a991f2cfbcf6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v11.0.0+2/libLLVM_assert.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
