[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "c3b9f3fa6c27f7d62f7fe020ebf3281d3bab728b"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "16c8ae86b5cfe8e7c173d667262d0d7fe73e58cfdd81a37215e586eaf093081b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e10036c7af2ef9b55e404b4549b2df140346c19"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3654dd441a37b2c724b2a363504e16ca11cb24771206aafd4afb6b4ccd35a8db"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9db0d03d9a04320e2197c5eb55f62ba8351fb894"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "781d6a930eee25b86c109c38477ec3ba531919ae294bfbbf9e5183d1cd1bf0a2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec0a2e0b4e935dd92f69f2ba4cbebbdb5da13804"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "60d0a65f698094c401af786f3fe5b66821a00c19b25cbeee5c571b4d4d10a31a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2cfa00e475a95ce9bc9297956be608a64438054"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1f5aab522c2dd0a3e71041a315957c9387eb50c5bb127801d8d83d5ddf0089c1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "592235fb426e297972afb4700d02fa03e8414b39"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fe4840bd4c9b89bc56438f60b812ebcf047d3b5579c50cb7a7f981378ef27ac4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d16ec2027465c8ba1c746ac7e4c116ec53634246"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9368f5df2d586a23cba3c1c246d3e3105de486a14d5adf38bc7086db0b796a04"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a7e08cbf9342ff4b649632d910cea81804caa22"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "212ece8245b9ff372f87e671de34d197d8ff92a8140f27d25c47ab93ee052968"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96529892d2ab52972c410c1e1ea56442951cbb8a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "63f742173997f6cfead95686f1074884aa610e4dd2ad294f945e1c97ec75d241"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b9fd90abced3af5b91f52df0e6892bd99ef8681"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9e33ac8f8e3719a0a7fadaeac30f643b4fa997565fbf457c48a67c262e50348b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12cef334e70d00fdfb054cdcb859dc28adf6ad66"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8b8f2ef4cafebfbd4fd7066427101f18280f2a64c4abfa560d8e10f8c2361c02"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1476c8f19c9ca59dd70e765e48f8c2a8d797d22"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "107f2eb5589152fcfc24cc8e4a4e66c85c4d39b1ab62d21abe120d5b74ff1d96"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4441a798527b4a95169f6216e28ea2d5cdfecd88"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "54c3fb73d577fbf367de3cf62bf5160aaf4c4a2355599c4d9d99e7a38e008045"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cf192f72090981dd69ee1b680e5fbd885b2ccae"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b21d273e862a5a89072f7f76eda7c28c94cabd0ebe4169f1aa914cf39098d375"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc49b0bb75255c2290f9615603649c3017e5d1c4"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "21d3d2c04ea5349f46d328f478472c4b58d651fa15020b10d71379ec031cac3d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f9b9e1f1f4f809346d77c22a2867b9fc3b437d4"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "247ca6908ecb3b22192d91b989acc9293022b9294a21db32fcdc413a25efa80d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e4cc45f4caed535501c0d2bc46abd0f8c09e93c"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3b2501a11b288861e807eb837c0d7d3b95032523aad884599ef51e3560b7286c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b18599ad5523ef7a763fa8e18a9359cceb823ff9"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "3f69c36f44a5650a316bdb6536c4d4df8234dc2c4b95470d0af96008ad0cdf68"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87b96f23d8afb704a86ac7c412c7a5abbc2096a6"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "229ddffa9d0daf279913b1fca243e30590e857bad4cc8051502fc6ac0f73f234"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29da549fb56b8d60b753189044620e42c43e6782"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5d653a5663bdf01d4755075eace344b86ce7a1ff5c9f945ca5c96ff0244f7106"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09cedf21057bc135fc9e43594143544b0b435d52"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "c38fda54767f57a7a0ca8c05b87a73c5656d85a2bdd8a3a1325087d6f36c9078"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "98270938ed1a9a4160a4cff7846462ec6c4bb21a"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "21aa1c0a771f7043a78bc1d4313f327b45d2d28a1b6d43cb07e5f3fa19c3b8ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82703d0c7c9418f86cdabef9ae34cfd3d033f028"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "2757f9b122b600ba919bcec5270925f056a975be5543b4ff3b9ef3db7e459834"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc666fdec102dd80afa7f7692bc864134d184019"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "019a3dcd1c6ae0cd6d99eaffbb0d82a54b3dc7a59671655a28062e4cafd8b5d0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "439aae3c0c3ec2b8f5e40e5f75cd578fdbef810c"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "68b9ad0992a3111eefe246851151419d6978bb7db46ee0f564bcaf6ee2db3a49"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "988b50f523972d3117b1a5fd3e6e71f41ddf92a5"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "73335f58ba4fa85cfa1820776ce05ccb31851ed0d9cf1e5399058730f077be59"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "f479b6ef69cc24ae4da30a2a0a3883e4e4326e35"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "b0258951f3e3bf16d99c63d68bd103a6e26925abfb5d8b727a59dd256863717d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a03c9d6daf82210e034bdfc14874ddc16bbe1d0b"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "43219aecc877f3931d164f07d5d647dafbb706431b19740572bee6f5a69cb4ae"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5ebf7fd7c6891676ec452fa4d70d341caf00548"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "36d50370e23921c675157787e02d73b1f9d3cb7f3bb9afd09f26a3f065abdca8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+0/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
