[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "170a7a52ed5feb1246a312283b03f0ef1e3ad38e"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "eac73979c322b4407e596a235b8b2d20c6331d7ab13b449617bdd89a2498374a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "430794be4b7418a0e2bb50dc354e319adaf5e387"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3123692270b24cdbe4bb03ee4502b8d33f40d7088062efd00f0083093b90c740"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ccb204266077619350700ebff63074bc5ab960e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "608e2fd5996ae2192d172ec72f31b428fa71c500332e896352529877097adec5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc05f7d70c62f8e3015cce74073b65574511ab60"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d2da3003bb071bf00e2eb3e8c5061570a31af14838f8ac600586eb4df9aba526"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9598c49b9f1910d40efb8db4f2f17c759aab6848"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fbebd56acce4d05795e9e6b35a0bd235e5ababb6ddaac94c15da16301df4d564"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b9c55be15beefb52a913d7ce87c4e6da0d5a900"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "edbfce958ea5aa83c0ba224dbdd170b72b1092cc5c309fa80d2cbd06eae4c4de"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efaec8f7222004a07b5d32cb4a43a5d72af8e33a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "bc3afa08ab8455018843f012896a8f00b6a0f1bc50a5eb56211a1f7b36f50ea2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "592784305a87aef56a625d37eb4b38f378c0d40b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1b18a8c3fafa8fa227c9e21ef62d5744e5784fafa368f15efba6284d47c9046e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b569e02302742237f98153aa29c20ea8f0fa9b7f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e21f65b95a48eb90ffa30fe043fff9bb4cd5924117273fb8a17a970a71457ba5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abc41d1f89b0aa32257a7eca41518a0983842fce"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fa5b6e99d31366120cf653aa1dac9c6fdebeaf869af2356ccb23bb22224f3ab5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a24812fe55f96904122ff6d73567d64cafa00c2c"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "6cbf16e34cd4a3ffae05e61f5243fdc3e7ce7f53eadc52ca14b789d0048d3d49"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3895595a76332acb2f2041860708e721ae5cd2e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "50bdfd053435d972bcd3910edca870e63d36e2aabf1d0f5d0101c63c06b7042b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d58520fc1e24b0d47304a404e384fd7c5e2147"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7ab93f47d8158a0d85bbb8615bedc0d2dcbbf64378b1a202c998bfcb59be8efc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ca5ea913c0d40521a9fc3adc664e1b769c31d26"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ec3430e3ab4d954d66b0d9c5509827d80b28574a31e8079c698247bb9655675b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f55b829455e9f771e81f71a82960f04725f2d26a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "cabdaf105218b32ec1205145d27dba9adc942d8bf54ee96b3fc4aff8ea681b03"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2490e434552a9cb72175ddbce8453569022a8bc"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e673fb5d19494d57ee0150acc1fb4c53985f55487a05f603653f9e2ec1ea4389"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a975a5e1fb8211dc4411178f7addcdf8deba7d1"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5217c8e8c3e7fb4467711c5e9c139e9a4c87e2257d812e0fbc482532c5abe932"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac63b6905dbf50d1aa8875b8219f225a039f3320"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "30365a3117536f8edbd4bcab0820722d131c93b0716b78a9a6538db6492a7529"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "715dc94de2aab543143396b5cf0280e9556f819c"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "51655468042bca511f7c4f447a10b271ede2039c9798ac5200f6d70fda1a6007"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32de7ce2230e42bbd47d8bbc269621eb65a2df5e"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4b76baeb5d73e55d561b48e8bde875de7931b6f7ddef5115928ca4622d432c65"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77139899dc4efebc2c489421b32673848b160cf7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "fcae15c2b1a1bcfaa08ac250527caf897e3213c3d6a0ce1eb6c74d028f04be26"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "ac145353c41bced00fc95d14e69b63b95a7a0cf1"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "8211b5b498053fb910ee22a1f01c2f39e36fe3cad239d48a3e2e869980ab5f7a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55733ff2fd3c7ccf066129e697f78a2b6574c9f2"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f9f9a4da3bd9ff722fcd163e79f93f7b865f7ef91e0415df71b603606a936d46"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10f496db4546384bde9e0b9988459363b116cd73"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "83763ab944694261f747cb9dbe8675d3ac846446817b95d337701f5af1fe28a6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5277796ae1e404445b2e26abca124d141880da7"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ceeb80eaa5f7cb51a5a6d0236ebd3f635950f6605c5f3fd94b6a1ec17f424c52"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50ce6385775542ce446d71816a22582663496e07"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "06390ec7e434e3b978f0a864a9606fbe2f7967168d10550a55cbe8885ffbcfee"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "adffaefd9328d071bdcc42bc717ab3f0bd07cc65"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "b50cdb47d17387f8f7c3f99c402ec524deeecd1563fcf72a3e2d5adda8633f3d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a877f27773ee6b08dccb6379632f01a9411df328"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "598502a7984293b5fcf53105f3dbf6f1b6c908ef2faf83a647e728e2e9c41b14"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd4634c312bbd26a8d59c36a62ddd4325d7e1133"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "8ae0d33634a8ddb273691c173de1f3b30ab59c87e497b783b73a8ca03c5cf934"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+1/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
