[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "ca878104142226f1139df0548a92d21ccbe1f0b9"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "2822ffb3fc63d57fbd9167647d426d01ff3a2134c445efc681764a6ef62edf33"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c0472d4c0da5e75cace9b9956d30987fa50cff5"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1ff61361a2657f935070e166980528f6f21b6d1be54760002965217ba8bc9ea8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad0a7c1871801c121193ab65c0cc343bdb4e9604"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8cbb612a56b841595e33953efcf1d3038c7c3296e2000a8466d8039c348e39be"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22471988d47aee189133f18cfb8ed2918bdddb8e"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "c6303567f059942ce2aa8e0ea094c69fd5ca8e9ebe5f1ca4cf96c1635ab2b93b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39023710aa88abc97958b3b8d86051e9b5a32000"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "63cf4de1f61462478c695f5a6c52d743297e2a9b7c00b1712a5daaf53e56566b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f49d67388e0628ec4f6cd5b5713d1d33f8d8bcd7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "686fc29427ad4c50796308a1f5ea0b16e9b6e2388dc2a23ce48679e66d215880"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aaa2960c2869845469593d803b5a729c6661abf"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a24612da752de98fc3ffaa862fbef6eda74cd1aef5cf47fbc82451339d7c2d52"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4244b8f40104120611c354cdf1cbe2215f7e72ab"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "36816bfd9201b8cb77747bafe9cbe27afd4de8d5a556a3dc8071acb5460a1d32"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8fcf51e4d3ecd1479dd6ae3b8a4529e3102c4ce"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "92d42be7cbd05f3e312438d97970a96ac8abeaef744108a9ff613d62639dc13e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa7e546cc11375b850b45ce12b91c51a4246b2cc"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4fafa3c3413f2adb78320c335bd9314651a412d459fa257b9131f47f5ebc9b3e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71b49359f6f8655e2879de86aa931b7af24159fb"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1db4bfbbbd7d08dd1543e26e5fbf0a41a685db09b4eafd1e57df831fb4bf10f0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a826b4c33ae80690bf7ae008c2b7873c00e9d5f4"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "eb24ad1465c2ef83f68c05ea6cdbd01b4dfb68ff260aa1616b30b5de67fb87cc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29d11f14bae1d3849c0d08c332100be39b5d7890"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e173ae4e3fc517f7d63ae0662230f7a7336a192bde2f9b182be36c790542796d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84e44faf99e5f053cf7a2447cd0b8d58cceaf8e1"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e37b99edf8f1f72c68a0deee37470a92953cac66af6be7bf2679ec87ba44ca3d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36f9ff72aaf70ca3f369eb3d69d70c2bb6485747"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "cf178b3328fe2beda5cb63155e1418ea30cf33a17a53fa5e1ec93ad36d784425"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3405f999ae3c6a0fdc26f83fdafd2a6399b57fb3"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "278bd442eb355b85a8dfb669d59786da1602e7021a9ce3fa16b4ed088b78f06e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8712560914e8d16a6664d3114835c73a3026ede5"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "5c4836fdf97e51759bb3cb0e5473edddf7975c9d4773c8fce4cb5e497dac99a0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21a5b77815ab90d0d6224bfc17d9af3c21121945"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "e2dc174da0f13bec02402cc0344fbc47df824456b209983bcf247116292d9daf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ade2ea0b4cab44fd8848eb1c252eff74fa37791"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "8c35030d4ab1fcc4a265273fc41fd249e47bce89f0d78d9fbacbbdca3cbd94b7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84ed1eb9e8c0a1a0a44e57672cb90cc801ae7e70"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "011219c30583d137085e3625100988512c89ff6ee6c1ec9bdd2c50761834ae8a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98f704da38df4e67746765f763fc105436f2c39b"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "cbc809a31c5035b93b207b0f8302394d7cdf58af5e236829433905b531542e45"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "42f3a7a479f1f672f808064d8231f2835432cb92"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "3e1d82b2f81e77cf0ae8e5a2c4ff5d8fd38dc40ac32b9410d87a3112ecca7ac8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcf9ede5b9b436cfa4d02d5cdc89248d3b0fc78b"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4f92d9ad1a82ff363df917185bfd0c5c08f3e5d69969ad9b6cc40637a40fbab0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af57461a2c0c9b9ad28fa9e325e632238ac23b1f"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "55a355bd5c148a69246611e87b888c9ef5c7ad350ff9beaf2ab4788829cf2c91"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dae988eb274f07d6d6a56ca30538c4d8adb63161"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ad331fd815d848310911721b06d87e8e5983c536c390a008ebe75c42e2316c3f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b4dd5a3575a3029e1f4c7b898f618723eb0a17a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3dc6d57ab3d6249404518e038aa102bd4af2f2a7f3eea029b1415d779a22d808"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "fe1c26cd38949399d2d4980d0d82fa466782c964"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "eb549a639dfa788fb0532111ff30f6a0bbc898e4d533d0965eaaafe222b441a4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f20d455d16241a63694442cb75f572ff2b3f1f4"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "b6af5a4954fb28e66fb69c5982fa0b7228b5c20caf5df5e4be0531bf4f47f359"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc129dcda6cc0df1898f3a019289ad691eb756d8"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "b91abfc02b149b02adfc958f6621e4173bf3c6b23a0a5adce2d64e36ef7144e7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+4/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
