[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "e5ff41ec48d9f9e16227937980c0117d60b35698"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "7500fb8becea17f61d934a558c258a8ff435442c55937a027845d53189d5d534"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b3b5a888675eff04c013cd0048af22508733e72"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7d7952a93f6d3a9f0d8276f353040e06c347ac84ad19afadb3016e019af2187d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a77b70ac3e05aeb948f5cff355912c232f06076"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "6620b5e8e483b50a3bafb7227c42b02bf2bc1172bacf9fa0786e93170ef44c7a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4955cb365d202ff975b9859aa0ed49d4ee653282"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9b9cb983771f3b6882f5bdd58eca5e175f71e8dd88f63c9530ce1bf70edf793a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59ab313bf27ef045fcdba8dfbbbdcd12b5d6eae4"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9d2a983d9bd50fa581252d38a9be1c92e886505185c1039f67de312b60fe147c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0f87b7e98dea99674d422e8571096057ec83120"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f579c72edea53b2c1b704b18f8da29398c97ef306ee3afa67744c744d79aacb7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5b19d10bb04809b6a537cdb3618017627bc10fc"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "31e39f510a8032a6e20933a68edc52c33cfcc9a725428b5301a9b020cd6470d0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7f72ab39a920b9f922d5fe25800afc7e92e0801"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "6ecaca6f70d29de84565f740914b3749b70f09d14da513b264cf6b1757e183fe"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bf4fade0b247a2ac8d3c6814f7c8c043b9b5ddf"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "88309d2875b59ea10d79748a9a70c13873abed4c8712d917b1cb1dbf92f747e0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7c9f46efd1e6430882555905b6527623d0c5964"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "086f0876ae4ccd70085c3ee66d682e383d1771af4b376f9316b8cf112b21de7c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69302b531ae4798436e21674a8a8b65d2e991aed"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "075470b8b65a62cce1329b62158d2c9f4013f4aeffa0b90d4a3257129dd264bc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b95803f982bca239f739fea66bf3c51cbd7cfefa"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "7923bd4466962dd6c4e215de0c95ac065978c379776faf38c132547ec8cce31f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b5a38514ca817f5a2d7447ca1f7883fc3668303"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b7c327b8e051c650fe8b647c74c925950262e31469c79bce6bea9d019a6501de"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7d766f7dc344dd441a3c4d7c130e4a0effa670a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d5ff11ac6da7be978db8acd7e613755e6645ec8e45eed9de71bf1d056500ddd8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a31534842509a15f3a6df16072497076527a6497"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0820197db4f544e91950e2451fa7e237e5ebececa05e853e798c6b4339dab62c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4bee93f15b2cbfe75a7672e22a45aeff0164f41"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1247bef90da99262fc93b18393a082414d987e8e41f1219fe239ed2417ee118e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dfda2881f2c078ff72f4a36517739aacb62802f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "bb797c64a180fac24c774d7e4ce3e5ee9771a94880087be7f1ddc274126d946e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61cbd7e79b45141c5e728fe76fea5c3696818455"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "e67fe6cb15c32884020d9160acbca1d19c145f2cd050ca089761fda10968097c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87c091092797c9e2dc82af27f6f31c0dcf279340"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "4ceb2db6ae91e1f0da8d8a3d712a90b3c7e9eb7c1625328bdfeacd790760c180"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a553a4ef7de6b3ec114de6041b95400d8add40c0"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e1543d1140a8711a53ea77cb8932de015948bab9e14362dcd35e019013af9eaf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e905940b969009894b11dab1f670d7708207dd29"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "be029b3b13b68a505477e5634c5881d57ca5ac6e69e2719aa8bd99cf0283160b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "797e56cde89b22cb92416df462dfb79d36d29244"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "807f5b4d39abdb4f49d04307feb3a2d3404080c01a11621fc40451e9e189b166"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b69d90b274e066600797e9df9dfd1b1d5743348"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e08957db9e74fad7f02898f146efd7ea18bd1dc8d60eaff085a784aceb1e6ea1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b6c25058a131c1962601d21c29aa97ab91ed482"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8e54a51ac874cfb87d1d2c61490d699edfe542d1413bda624cf26b190363f4a9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68d1978b4079cd0e5890ccca65d40cfe533319dd"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e8edd52f711a50dcc147bcd4c522579fd13cc02a1f51890ebedd65ea931b4269"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b41272819bddc2ef046c725f8f14cef0eb8ee18a"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "f82e0a0a60fb1ffad9088474d824ea5eabdeb1a648fd173e878eb03db5b5c32a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "6f222fb006c4031c8dc4ebcf26414bdb994ee250"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "6040d73adbeaaa707f3568a134f7710843a4e3813c8281708e7039a651f3985a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "001b442d2a542cfc5d14c467228d4c4b81e8b6ea"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "ad01386d63aa48734bea683dc45ce41f7be2afb3679ad39eb994989380c88937"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25213e66dcab84c5d473e83fd61b623ceaad6a12"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "c81569bd239ef424c540ef57bc6db500faa57f186e69b4174caead042a51a9c7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v13.0.1+3/libLLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
