[[libLLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "398c04d21f12bd24209f4eb5cffad697497541ae"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "6db3a373f7be604b87b2e334a916d07c64742968f9b84219dbbb8a5409ffa40f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d07df422f89a7ed068e7053b0adb25c60e7bcad6"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b65f7c54b6146908eb152a048ff0f2f48bc2f6f85f7fabc6de466251e42c9841"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fff73bed7a359f91800fbfac425f008e46466996"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d9e36cde9598d778e00ac01b57d26ffaecbfb7171c826118a7951ed02ae43e99"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e436a9fd7f2110c1b87e08d7286b33760d04a54c"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "b901a2ebe9a96338519b32332564b023e15b98d70b0b9452cc16e91288e9be96"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1af2883b70e33253d7531e87971d4514731bd1e0"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "89732c2f9e5a3ec6342fbb4351bdd9d3b222741c758c5209d53935c032aa426d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02d232616e4a09701b656c76775e3d8ae0884994"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "c33bc9ff29240455e2c5442adb4fb71962217818c6ab8f09d2378babf741db2d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d97579c8f507690dcfd32989c64bf1a2616e95a"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0b4377eb847f1d2e511aaa77a074a79d46d980f9eaed59e5758ae37796f77b57"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7966c196863ad506fe694db00df26d4944741d2"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4d88d3aacb20fdc9dce0672e0e94708f1cea9981643a30f19f1e07f2b1c5f819"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cba1f79910dadcf4c74ea88e0fa343fbd1ef0a9f"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0f42d3868abea3cb4ac7bb240fad322eb9f7a214156d510c00a02623cc8afb06"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fb1291229d20e46718e366004310a8b459978dc"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "1ae9e6b9a627c1d83b4b7bf46704d4314314cebb663e1f77833c3ec1395541da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d481dfc1db4c40812b9f936797d20e7cd1c6ce84"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d3d2aeb5a72f8c3a1b85328ef12b60064fd1e81fd70ab7dc854e0b054f61af20"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0095be614d9a10a678e25489f9f221326b1aa6b9"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "0cfca25a477cf82f65277ce488ef0c5e36a14d0ddbac3cb1b1ff6302e3018617"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9ce83f430f5e88000c9aae6185080801d56f6a9"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "9cb4b2b2c1add44220a2b1fc8959af3d25785bbdef10b992050fdd07192cf69f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2255f729393d173135eee3787313936c9dde4367"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "d7887d43c50d91711df24d710c4d20089b76c8a062394db5ff479b22da34f06a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c617aca4dc7ed82cd228435dad81ab8fc26f7e97"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "3d541ef6245d414e6fae01a739174438bdfe5ed814cbd1918ef13f9926208b21"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbff0fced3ace4554c60061827ef7385aa2e63c8"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "04c84c52746efb47943d618c04f582a4aef32a4570dd7381889094a18626df36"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd3791caa9992eb0c3e5fa0d7b262ae28862cd31"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "8c215b6fca063c3b70b9f3bf4a08f7c3dc294e6d0253259b461fff38a45d11e6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c48096d7968f9a5d081be0b99d65d0b5678aed5"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "da8f7375166f34ede1f5dfb95259866c6a166e36e57e2d3a894f3ec32d0a288f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b206076d634cf9d64354b0523811de5ede32fd65"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "5e582542d0aab3571160ccf4c67170a5b68b99bfa36590db7f2a8db82dd4b65a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17d8091960e506c1df1dca4f63f07694dd46f6f7"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "a693591621d2fa6b88bbc9dbc6446053fb0ef1bde692ed54735573cdfee53489"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aec4d9af286a09363c07dd45fbc9993a321b7f33"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "e15d55359093fe404c0a838c2c17caa5c78416a0106f88d8d32265a6c45c59a3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "8fad040be2f2dbf6d4606236310eece12ef4286d"
os = "macos"

    [[libLLVM_assert.download]]
    sha256 = "dc04f1fe0d609cca50ed7e95fe089640f4060f03c3778e40324e31f76206964e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef3f47b81358815cf9bcc26c4ea2d766271379e3"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "687c65be263138b6f2110957960c5bd73a271f4c1bbaf67706d7b176b24061c3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efca94695c5d07faf17ec75ff81b066ed99e4db6"
libc = "glibc"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "745ba071f5696911bc7b08a9bdb6b1c021a0809cd252e4a620af54e0a15be8ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12ffc9dd23fa8a2e780b0bc886dc883142a3029b"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "ddfbe5d1c3392ab86c3b3e3b9336e9fd24546ea98eaaeb483d829bd274bdbf78"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4eea8b579e111d6e36e81a5a7fbfdbb7c9a456e2"
libc = "musl"
os = "linux"

    [[libLLVM_assert.download]]
    sha256 = "4994de39feb2d837a353cd7cb14413b2c3e07416d49e4ec7ed9387978e7febec"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "d6d54d5e57a19cd886151c59e8116917e900cb1e"
os = "freebsd"

    [[libLLVM_assert.download]]
    sha256 = "f6e8ad453341a4a7f71d05b5353dbf2c8f1251184e00a36eaf6b110b614df063"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "608c2324f4d50f48e91b6f7c001507c8b4a8228e"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "5d3752ed7d7073e1a47a9c7547f3a1ec5ffd574140fd113d54d0db4ab21b4fda"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "795853fcc650fea3e88e96c7e3a3c0371a613ce4"
os = "windows"

    [[libLLVM_assert.download]]
    sha256 = "03a788d36016064e18169f105d4fe0991ea0faa35b4c6bf87f9d57914471cb47"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_assert_jll.jl/releases/download/libLLVM_assert-v12.0.1+3/libLLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
